作業目標:<br>
1. 運用索引找出需要資料<br>
2. 合併資料的分法應用

In [ ]:
# 作業重點:<br>
1. 分辨索引loc、iloc差別
2. 分辨合併資料方法的不同，因應不同情況使用Merge, join, concatenate

題目:<br>
讀取STOCK_DAY_0050_202009.csv串聯STOCK_DAY_0050_202010.csv，並且找出open小於close的資料

In [12]:
import pandas as pd

#讀取STOCK_DAY_0050_202009.csv、STOCK_DAY_0050_202010.csv
file_202009 =  pd.read_csv('STOCK_DAY_0050_202009.csv')
file_202010 =  pd.read_csv('STOCK_DAY_0050_202010.csv')


#串聯
fileappend = file_202009.append(file_202010)


#找出open小於close的資料
open_min_close =  fileappend.loc[fileappend.open<fileappend.close]

open_min_close.set_index('date')

             open    high     low   close
date
109/09/01  102.45  103.35  101.85  103.35
109/09/04  102.00  102.70  101.90  102.55
109/09/08  102.75  103.10  102.45  103.00
109/09/09  101.75  102.35  101.15  102.30
109/09/10  102.80  103.35  102.60  103.20
109/09/11  103.20  103.35  102.80  103.25
109/09/14  103.50  104.55  103.25  104.55
109/09/15  104.45  105.20  104.25  104.95
109/09/28  101.35  102.30  101.00  102.30
109/09/30  102.75  103.45  102.60  103.00
109/10/06  104.00  104.35  103.85  104.25
109/10/07  104.00  105.00  103.50  104.80
109/10/08  105.45  106.35  105.30  106.20
109/10/12  106.70  107.70  106.70  107.05
109/10/19  105.65  106.60  105.60  106.60
109/10/22  105.70  106.10  105.50  106.10